[project]
name = "ctbench"
version = "0.1.0"
description = "Benchmark of methods for cell type annotation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
hello = "ctbench:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
